In [74]:
import numpy as np
from sklearn.datasets import load_iris

dataset = load_iris()
X = dataset.data
Y = dataset.target

In [75]:
X_d = np.array( X>X.mean(), dtype='int')

In [76]:
from collections import OrderedDict
import pandas as pd

Iris_data_d = OrderedDict({'Sepal Length ': X_d[:,0],
             'Sepal Width': X_d[:,1],
             'Petal Length': X_d[:,2],
             'Petal Width': X_d[:,3],
             'Label': Y})

data_table = pd.DataFrame(Iris_data_d)
data_table

     Sepal Length   Sepal Width  Petal Length  Petal Width  Label
0                1            1             0            0      0
1                1            0             0            0      0
2                1            0             0            0      0
3                1            0             0            0      0
4                1            1             0            0      0
5                1            1             0            0      0
6                1            0             0            0      0
7                1            0             0            0      0
8                1            0             0            0      0
9                1            0             0            0      0
10               1            1             0            0      0
11               1            0             0            0      0
12               1            0             0            0      0
13               1            0             0            0      0
14               1            1             0            0      0
15               1            1             0            0      0
16               1            1             0            0      0
17               1            1             0            0      0
18               1            1             0            0      0
19               1            1             0            0      0
20               1            0             0            0      0
21               1            1             0            0      0
22               1            1             0            0      0
23               1            0             0            0      0
24               1            0             0            0      0
25               1            0             0            0      0
26               1            0             0            0      0
27               1            1             0            0      0
28               1            0             0            0      0
29               1            0             0            0      0
..             ...          ...           ...          ...    ...
120              1            0             1            0      2
121              1            0             1            0      2
122              1            0             1            0      2
123              1            0             1            0      2
124              1            0             1            0      2
125              1            0             1            0      2
126              1            0             1            0      2
127              1            0             1            0      2
128              1            0             1            0      2
129              1            0             1            0      2
130              1            0             1            0      2
131              1            1             1            0      2
132              1            0             1            0      2
133              1            0             1            0      2
134              1            0             1            0      2
135              1            0             1            0      2
136              1            0             1            0      2
137              1            0             1            0      2
138              1            0             1            0      2
139              1            0             1            0      2
140              1            0             1            0      2
141              1            0             1            0      2
142              1            0             1            0      2
143              1            0             1            0      2
144              1            0             1            0      2
145              1            0             1            0      2
146              1            0             1            0      2
147              1            0             1            0      2
148              1            0             1            0      2
149              1            0             1            0      2

[150 rows x 5 columns]

After we have the table, we can apply "One Rule" algorithm based on the frequency, which a simple, yet accurate, classification algorithm based on one rule. 

The algorithm is the following. 
- 1, For each predictor,
     - 1.1 For each value of that predictor, make a rule as follows;
           - 1.1.1 Count how often each value of target (class) appears
           - 1.1.2 Find the most frequent class
           - 1.1.3 Make the rule assign that class to this value of the predictor
     - 1.2 Calculate the total error of the rules of each predictor
- 2, Choose the predictor with the smallest total error.

http://www.saedsayad.com/oner.htm



### 23.6 Homework 

Complete the One Rule Algorithm

In [132]:
def one_rule(xi,measurement):
    yi = Y
    
    freq0,freq1 = 0,0
    
    greaters = []
    lessers = []
    
    for i in range(len(xi)):
        if xi[i] == 0:
            freq0 += 1
            lessers.append(i)
        else:
            freq1 += 1
            greaters.append(i)
    
    #print('There are',freq0,measurement,'< the mean and',freq1,'> than the mean','\n')
    
    gfreq_0,gfreq_1,gfreq_2 = 0,0,0
    lfreq_0,lfreq_1,lfreq_2 = 0,0,0

    for i in greaters:
        if yi[i] == 0:
            gfreq_0 += 1
        elif yi[i] == 1:
            gfreq_1 += 1
        else:
            gfreq_2 += 1

    #print('Out of the 24 flowers with',measurement,'greater than the mean,',gfreq_0,'are Setosa,',gfreq_1,'are Veriscolour, and',gfreq_2,'are Virginica','\n')

    for i in lessers:
        if yi[i] == 0:
            lfreq_0 += 1
        elif yi[i] == 1:
            lfreq_1 += 1
        else:
            lfreq_2 += 1

    #print('Out of the 126 flowers with',measurement, 'less than the mean,',lfreq_0,'are Setosa,',lfreq_1,'are Veriscolour, and',lfreq_2,'are Virginica','\n')
    
    data_d = OrderedDict({str(measurement): range(0,2),'Setosa': [gfreq_0,lfreq_0],'Veriscolour':[gfreq_1,lfreq_1],'Virginica':[gfreq_2,lfreq_2]}) 
    data_table = pd.DataFrame(data_d)
    return data_table

In [134]:
measurements = ['sepal length', 'sepal width', 'petal length', 'petal width']
for i in range(len(measurements)):
    print(one_rule(X_d[:,i],measurements[i]),'\n')

   sepal length  Setosa  Veriscolour  Virginica
0             0      50           50         50
1             1       0            0          0

   sepal width  Setosa  Veriscolour  Virginica
0            0      21            0          3
1            1      29           50         47

   petal length  Setosa  Veriscolour  Virginica
0             0       0           47         50
1             1      50            3          0

   petal width  Setosa  Veriscolour  Virginica
0            0       0            0          0
1            1      50           50         50

#### From the tables above, it is obvious that sepal length and petal width are not are not good enough predictors. This is because in the sepal length and petal width case, all flower types are equally probable.

#### If we look at the sepal width, it can be seen that this measurement is a great predictor only for flowers with sepal width lower that the average value but not above.

#### Lastly, if we look at petal length, it can be seen that for flowers below the average, classifying between veriscolour and virginica is difficult. However, for those above average, the predicted value is mostly likely going to be setosa.